### ISSUE TITLE
expose a .createIterator([boolean]) function for bitfield iteration

### ISSUE THREAD

**Issue by e-e-e** [hypercore-protocol/hypercore#105]
As discussed in the #dat channel it would be great to extend the functionality of the bitfield iterator to allow for quick searching of either 1 or 0 bits in the bitfields.

I have briefly looked into implementing a solution and it should not be too difficult considering that you have already done the hard work with implementing the 0 bit iterator.

where the NEXT_DATA_0_BIT looks like this 
```js
NEXT_DATA_0_BIT[i] = i === 255 ? -1 : (8 - Math.ceil(Math.log(256 - i) / Math.log(2)))
```
a positive one would look like this:
```js
NEXT_DATA_1_BIT[i] = i === 0 ? -1 : (8 - Math.floor(Math.log(i) / Math.LN2))
```

I will open a pr when i find time. But as you say this is not super urgent.

**Comment by mafintosh** [comment]
Closing cause old and lots have changed
