### ISSUE TITLE
Change the {live:} opt of replicate?

### ISSUE THREAD

**Issue by pfrazee** [hypercore-protocol/hypercore#120]
Related to https://github.com/mafintosh/hypercore/issues/119, should we change `replicate({live: true})` to something more clear?

Eg `replicate({keepOpen: true})`

**Comment by noffle** [comment]
I'm fond of the `live` verbage for replication fwiw.

**Comment by scriptjs** [comment]
I am not keen on such a change. Live is sensible and intuitive. I agree with @noffle regarding "static"

**Comment by mafintosh** [comment]
changed in 10
