### ISSUE TITLE
Node keeps sending data after peer disconnects

### ISSUE THREAD

**Issue by bnewbold** [hypercore-protocol/hypercore#123]
I found that after a remote (TCP) client disconnected from a dat node, the surviving node kept sending data messages every half a second (debug messages here from DEBUG):

```
    [...]
    dat-network Uploaded data: 984105 +500ms
    dat-network Uploaded data: 984105 +500ms
    dat-network Uploaded data: 984105 +501ms
    dat-network Uploaded data: 984105 +499ms
    dat-network Uploaded data: 984105 +501ms
    dat-network Uploaded data: 984105 +500ms
    dat-network Uploaded data: 984105 +500ms
    [...] 
```

Doesn't cause any specific problems, but the node should probably recognize that the client is gone. This might be related to the similar sounding #109 ("don't send requests after close over replication streams"). It might also be uniquely triggered by my buggy/work-in-progress/non-compliant client.

**Comment by mafintosh** [comment]
Closing cause old and lots have changed
