### ISSUE TITLE
pass open error to `.ready` callback

### ISSUE THREAD

**Issue by juliangruber** [hypercore-protocol/hypercore#136]
What about catching open errors like this:

```js
core.ready(err => {
  // ...
})
```

instead of what you have to do currently:

```js
const open = cb => {
  core.on('error', cb)
  core.ready(() => {
    core.removeListener('error', cb)
    cb(null, core)
  })
}
```

I'm happy to submit a PR for this

**Comment by juliangruber** [comment]
See also: https://github.com/datproject/dat-node/pull/185

**Comment by mafintosh** [comment]
That's what we used to do, but the concern that made the change was that it would make critical errors not crash the process through the error event. What do you think?

**Comment by mafintosh** [comment]
I'd be open to only having the ready handler and then no error event

**Comment by juliangruber** [comment]
> That's what we used to do, but the concern that made the change was that it would make critical errors not crash the process through the error event. What do you think?

This should be for the consumer to decide - while appropriate for a CLI it's not appropriate for long running processes like Dat Desktop. And if the process should be crashed, you can still do it responsibly by handling the `error` callback argument.

**Comment by juliangruber** [comment]
Maybe wording is the problem here too, I'm assuming you're talking about the risk of people calling `core.ready(() => {})` without handling the error argument. Maybe calling it `core.open(err)` would help?

**Comment by mafintosh** [comment]
Ya that could work. Think I like that better also

**Comment by pfrazee** [comment]
I'm fine with w/e

**Comment by juliangruber** [comment]
should `open` return an error if the core is already open?

**Comment by mafintosh** [comment]
Closing cause old and lots have changed
