### ISSUE TITLE
Implement peer exchange (PEX)

### ISSUE THREAD

**Issue by xek** [hypercore-protocol/hypercore#137]
PEX is an extension of the BitTorrent protocol. It allows a group of users (or peers) that are collaborating to share a given file to do so more swiftly and efficiently.
https://en.wikipedia.org/wiki/Peer_exchange

Implementing this in hypercore will greatly help with connection issues behind proxies and in an instance the Kademlia DHT is blocked, as well as enhance the privacy aspect of Dat, since the peer list would be sent inside an encrypted TCP or UTP channel.

It would also be a great example on how to extend the Dat protocol.

A related issue, proxy support in Beaker: https://github.com/beakerbrowser/beaker/issues/682

**Comment by xek** [comment]
@mafintosh I see there is an extensions string in the first handshake, but I'm not sure how to use it.
I'm refreshing my JavaScript, so If you can give me pointers on how you think this should be implemented, I might be able to submit a comprehensible pull request.

There are other aspects of running behind a proxy mentioned in the beaker issue and I might be able to help with implementation and testing of those as well.

**Comment by pfrazee** [comment]
We're starting to formalize a process for extensions like this at https://github.com/datprotocol/DEPs. (Process DEP is in progress, see https://github.com/datprotocol/DEPs/pull/2). If you wanted to start a proposal using the template in PR 2, that'd be cool.

**Comment by RangerMauve** [comment]
This is really cool! It should probably go into https://github.com/maxogden/discovery-channel

**Comment by RangerMauve** [comment]
Actually, this would be better as an extension of the dat protocol. :x

**Comment by mafintosh** [comment]
Super cool idea still and have lots of ideas for this, but should be an extension protocol on 10. On the Discord if anyone wants to discuss.
