### ISSUE TITLE
read/write transformer

### ISSUE THREAD

**Issue by fsteff** [hypercore-protocol/hypercore#148]
To support encryption it would be useful if it was possible to add a "transformer" to a hypercore that is called on write and read operations (similar to a transformer stream).
Here an example how this could work:

- To add the transformer it is passed to the hypercore´s constructor as part of the opts parameter.
- On read operations it is called inside [get()](https://github.com/mafintosh/hypercore/blob/7c2005cf71badbd54caded1f42267ac887106dd4/index.js#L891), maybe as a "wrapper" function of the callback
- On write operations it is called inside [_append()](https://github.com/mafintosh/hypercore/blob/7c2005cf71badbd54caded1f42267ac887106dd4/index.js#L993)

But in contrast to a regular stream transformer it would be necessary that it gets further parameters:

- a byte-offset of the position of the data in the feed
- a reference to the hypercore (simply called using *this* as a parameter) to make the key management easier

Also there may be some difficulties I stumbled upon when writing [hypercore-encrypted](https://github.com/fsteff/hypercore-encrypted):

 - The encoding of the data may differ from the original, not sure if that changes some internal things
 - the get() function has to call _storage.[dataOffset](https://github.com/mafintosh/hypercore/blob/7c2005cf71badbd54caded1f42267ac887106dd4/lib/storage.js#L71) which I think may be a little slow.

This transformer feature may also be useful to implement other things  (like compression), do you have some ideas on this? 

Also, maybe I´ll have the time to implement it myself.

**Comment by fsteff** [comment]
Yeah, "hooks"  sound even better than "transformers". A more general api that does not sound more complex is perfect!

**Comment by fsteff** [comment]
Can I somehow help to get it working?
I see some of the hooks are already implemented, but not enough to support encrypting a hypercore.
To show how I imagine this to work I created this [fork](https://github.com/fsteff/hypercore) a while ago (already a bit outdated).
I have a lot of ideas that depend on encrypted hypercore/hyperdb(s), so need this feature.

**Comment by mafintosh** [comment]
Closing cause old and lots have changed
