### ISSUE TITLE
hypercore on ARM?

### ISSUE THREAD

**Issue by mathpunk** [hypercore-protocol/hypercore#164]
I'm interested in having a hyperdrive on my Android device. I tried installing the package on my phone via Termux. I learned that it depends on node-gyp-build, which depends on sodium-native, which is a collection of bindings for libsodium.

Since p2p on mobile is interesting to me, I wanted to ask if it would be worth it for me to investigate where and how to make changes to one or more of these libraries to get hyperdrive running on Android. Alternatively, I'm also asking if this is the wrong direction to take for p2p on mobile, and if there is a different avenue I should investigate instead.

**Comment by emilbayes** [comment]
Ping @jimpick

**Comment by jimpick** [comment]
I think it depends on a lot of things. The app for the cabal-mobile project works on Android, using "nodejs-mobile" from Janea systems.

https://github.com/cabal-club/cabal-mobile
https://github.com/janeasystems/nodejs-mobile

Right now, I believe the Android version isn't using the sodium-native package, and is falling back to use the sodium-javascript version.

I've been working on cross-compiling the sodium-native and utp-native libraries for iOS which uses node-gyp-build. I will probably build "prebuilds" for Android too, but only for the Janea systems version of Node.js.

I'm not familiar with the Node.js in Termux. Theoretically, if you aren't able to compile sodium-native, the sodium-universal package should load sodium-javascript instead....

**Comment by mathpunk** [comment]
To be honest the only reason that I tried `npm i hyperdrive` from Termux is, I've never developed for Android and I wanted to see if I could get something running by coding it up right on my phone at a familiar-looking command line. I can try out developing an Android app `The Right Way` and come back when I am ready to start including libraries.

**Comment by mafintosh** [comment]
works on arm now
