### ISSUE TITLE
Hypercore access feed remotely

### ISSUE THREAD

**Issue by IvanAbadzhiev** [hypercore-protocol/hypercore#165]
Hi,
Great project I need a distributed log for my project and I chose to use hypercore.
I understood how it works and it's perfect when I try with different processes on my computer, but when I try to use a computer in a different network I couldn't find the peer.
```
const hypercore = require('hypercore');
const hyperdiscovery = require('hyperdiscovery');

var feed = hypercore('./feed')

var swarm

feed.on('ready', () => {
	swarm = hyperdiscovery(feed, { live: true })
	var hash = feed.key.toString('hex')
	
	swarm.on('connection', (connection) => {
		console.log('new connection')
	})
})
```

In the **reader** node I have this code
```
const hypercore = require('hypercore');
const hyperdiscovery = require('hyperdiscovery');

var feed = hypercore('./feed','81299d1cfa07fdd427800abb00a12d3b264776f72aedc14da93c84d52a69ae04')

var swarm

feed.on('ready', () => {
	swarm = hyperdiscovery(feed, { live: true })

	swarm.on('connection', (connection) => {
		console.log("new connection")
	})

	console.log('Connections ' + swarm.connected );
})
```

It works perfectly when I run it on one computer. 
I saw that you have a lot of similar project I will try to add more examples when I understand it better and resolve this issue.

Environment information:
Windows 10
NodeJS - v8.11.2
Hypercore - 6.17.1
Hyperdiscovery - 8.0

**Comment by fsteff** [comment]
Are both computers behind a firewall / NAT?
In this case this could be a problem.
As far as I know hyperdiscovery does not support nat traversal.

**Comment by IvanAbadzhiev** [comment]
I tried with 3 Cloud VM instances and it works maybe the problem is with **nat**.
I have other questions:
What is the difference between **feed key** and **discovery key**?

**Comment by fsteff** [comment]
The discovery key is a hash of the feed key.
(the feed key is the public key of the keypair used to sign the data). The transmission is encrypted using the feed key, so that someone crawling the dht cannot read the data.

**Comment by mafintosh** [comment]
Closing cause old and lots have changed
