### ISSUE TITLE
Error: Storage should be a function or string

### ISSUE THREAD

**Issue by gaspecian** [hypercore-protocol/hypercore#169]
Hi, i'm trying to run : 

`var hypercore = require('hypercore')
var level = require('level')

var core = hypercore(level('teste.db'))
var feed = core.createFeed()
console.log(feed.key.toString('hex'))
feed.append('test') `

but it gives me this message:
`
  if (typeof createStorage !== 'function') throw new Error('Storage should be a function or string')
                                           ^

Error: Storage should be a function or string
`

**Comment by gaspecian** [comment]
I tried change to : 
`
var core = hypercore('./teste.db', {valueEncoding: 'utf-8'})
`
but it gave the same error

**Comment by emilbayes** [comment]
@gaspecian Which version of hypercore are you using? The above snippet works just fine for me with 6.18.1

**Comment by mafintosh** [comment]
Closing cause old and lots have changed
