### ISSUE TITLE
reproduce a hypercore from external data?

### ISSUE THREAD

**Issue by hackergrrl** [hypercore-protocol/hypercore#172]
Imagine I exported a hypercore to a plaintext file, for robustness and ease of reading, as ndjson:

```
{
  "key": "hex_public_key",
  "seq": 0,
  "value": {
    "data": "foobar"
  }
}
{
  "key": "hex_public_key",
  "seq": 1,
  "value": {
    "data": "foobaxxxx"
  }
}
```

Is there a way to construct a hypercore instance + storage from this with the current APIs? If not, what might need to be added?

Context: thinking about USB sync files for hypercore / [multifeed](https://github.com/noffle/multifeed) data, and future-proofing data exports so that other systems & languages ignorant of hypercore could still benefit from this data (while also being re-importable into hypercores).

**Comment by mafintosh** [comment]
Closing cause old and lots have changed
