### ISSUE TITLE
Handling conflicts

### ISSUE THREAD

**Issue by EGreg** [hypercore-protocol/hypercore#174]
How does hypercore handle conflicting transactions submitted at roughly the same time to different Dats, both signed by an authorized writer? Does it require a quorum before committing a transaction, to avoid forks and netsplits?

Also, how would hypercore handle a fork that is discovered later due to a malicious Dat nodes colluding with the writer to prepare and reveal a fork much later? Is Dat Byzantine Fault Tolerant against malicious nodes?

**Comment by pfrazee** [comment]
Currently any conflicting writes are rejected by receiving peers, causing the hypercore to stop making global progress when a split occurs in the history. 

I’m currently proposing a data-structure-specific resolution process. https://github.com/datprotocol/DEPs/pull/43

Hypercores are designed to have a single writer. Splits are failure conditions.

**Comment by emilbayes** [comment]
@EGreg Are you aware of hyperdb? What you describe sounds more like hyperdb than hypercore. As Paul said, hypercore is single-writer, unless you have the secret key in multiple places, but doing that can cause forks/splits which currently is pretty much undefined behaviour.

**Comment by EGreg** [comment]
I am not aware of hyperdb, can you send a link?

I am interested in working with some hypercore contibutors to understand hypercore code and see if I can fork it and build upon it and contribute back. Is there documentation on how hypercore code works? What is the best way to start building compatible extensions to it?

**Comment by iamyellow** [comment]
may i ask what the meaning of 'writer' here? i mean, if i have a multiple remote peer feeds replicating (bidirectionally) to a central / server feed, are they considered writers? or you mean feeds actually using the same random access storage?

**Comment by emilbayes** [comment]
@iamyellow So in hypercore every block is essentially signed with a cryptographic signature (not exactly what happens), so a writer is anyone possessing the private key required to make a signature, and hence write to the feed. Despite it being possible for this key to exist in multiple places at the same time, it is undefined behaviour if two distinct places sign at the same time, making a fork in the history as Paul outlined here, and is proposing functionality for resolving: https://github.com/datprotocol/DEPs/pull/43

**Comment by mafintosh** [comment]
Closing cause old and lots have changed (see autobase for something like this)
