### ISSUE TITLE
Extending Hypercore

### ISSUE THREAD

**Issue by EGreg** [hypercore-protocol/hypercore#175]
Our project is looking to build a  distributed system that allows people to collaborate on group activities with MULTIPLE writers, an imperative language for validating transactions, and end-to-end encryption (see qbix.com/blog). We also plan to add Byzantine Fault Tolerance to prevent forks by malicious writers or validators. To do this, we will need to implement a system that lets participants in a swarm make complaints about data supplied by other participants, and each participant must make a decision who to side with, etc.

We found Dat hypercore to be the best starting point for what we want to do. We can use any of the swaming mechanisms (hyperdht, kademlia mainline dht etc.) but as far as the merke log, does the hypercore code allow us to extend it with the above features while maintaining compatibility? If not, we may have to build our own merkle log from scratch, using only the swarming. We’d like to stay as compatible as possible to SLEEP format! What do you suggest?

**Comment by martinheidegger** [comment]
`.replicate()` of hypercore _(the networking part)_ is isolated in [`./lib/replicate.js`](https://github.com/mafintosh/hypercore/blob/871271549ec2bc685137970ad9bc29794f23055d/lib/replicate.js#L10) 

By providing your own replication `otherSystemReplicate(hypercore)` you should be able to add your own networking stack while still getting a lot of value out of hypercore.

**Comment by mafintosh** [comment]
Closing cause old and lots have changed
