### ISSUE TITLE
on("download") does not respect valueEncoding

### ISSUE THREAD

**Issue by orionz** [hypercore-protocol/hypercore#177]
valueEncoding seems to work eveywhere except on("download")

```js
  const feed = hypercore(storage,  { valueEncoding: "json"  })
  feed.on("download", (i,data) => {
    // data is of type Buffer here and not parsed json
  })
```

**Comment by mafintosh** [comment]
ah yes. @pfrazee wdyt is the right approach here? we might rely on data to be a buffer here to report download speed a ton, although i can see the confusion about it not being decoded

**Comment by mafintosh** [comment]
let me try and run dat with this fixed tmw and if nothing breaks this is an easy fix actually

**Comment by mafintosh** [comment]
Changed in 10
