### ISSUE TITLE
Remove dependencies used for node <4 compat

### ISSUE THREAD

**Issue by mafintosh** [hypercore-protocol/hypercore#193]
All the buffer-alloc stuff, etc. Should be a major bump after.

**Comment by ralphtheninja** [comment]
I can take this if you like. So remove:

- [ ] `buffer-from`
- [ ] `buffer-alloc`
- [ ] `buffer-alloc-unsafe`

?

**Comment by martinheidegger** [comment]
Do you mean to also replace "unordered-set" (used to store peers) with a native `Set`?

**Comment by martinheidegger** [comment]
I havn't done many performance tests recently but made one for this: https://gist.github.com/martinheidegger/4ba55728c3e049f03a7536d4b64b1949 should show that `Set` has a O(1). The performance of `Set` seems faster on newer Node versions and the performance of `add` is quicker in comparison to the Array variant while the `remove` is quicker in the unordered set.

**Comment by mafintosh** [comment]
Fixed in latest
