### ISSUE TITLE
The behavior of createWriteStream({snapshot: false}) is unclear

### ISSUE THREAD

**Issue by corwin-of-amber** [hypercore-protocol/hypercore#218]
The README says:
```js
  snapshot: true, // if set to false it will update `end` to `feed.length` on every read
```

This is not what it does. From looking at the code, it only affects the first read iteration, and only when `end` is omitted or equal to -1. In which case, it causes the read to terminate resulting in an empty stream due to the following line:
https://github.com/mafintosh/hypercore/blob/52267168b475c41e3ae10a2cb14c4b31da75570a/index.js#L1171

**Comment by mafintosh** [comment]
Closing cause old and lots have changed
