### ISSUE TITLE
"Remote signature could not be verified" when using clear()

### ISSUE THREAD

**Issue by rhodey** [hypercore-protocol/hypercore#224]
I have three peers, one is the writer, another is an websocket server, and the last is a browser client. the websocket server replicates with the writer over WebRTC and then proxies that into browser world via websockets. The hypercores I am working with are very large so the websocket server only holds onto a manageable chunk of the most recent blocks, this is done by using the `clear()` method. the program looks like this:

```javascript
function download(archive) {
    let start = Math.max(0, archive.remoteLength - opts.capacity)
    let range = { start, end : archive.remoteLength }
    console.log('download begin   ', range)
    let read = archive.download(range, () => {
      console.log('download complete', range)
      archive.clear(0, start)
      archive.update(() => download(archive))
    })
  }
```

All hypercores (writer, server, client) are running in sparse mode. At the browser client I get error "Remote signature could not be verified" before even requesting any blocks. However when I remove the use of `clear()` from the server this error does not occur.

**Comment by rhodey** [comment]
also of importance: changing between live and non-live replication does not affect the outcome.

**Comment by mafintosh** [comment]
Anyway you can make a full testcase that showcases this?

**Comment by mafintosh** [comment]
Closing cause old and lots have changed
