### ISSUE TITLE
Cannot use hypercore in browser

### ISSUE THREAD

**Issue by tjmehta** [hypercore-protocol/hypercore#234]
When I create a webpack bundle that includes hypercore I get a runtime error in `noise-protocol` on line 8 of `cipher.js` (`sodium.crypto_aead_xchacha20poly1305_ietf_KEYBYTES` is undefined...)

`noise-protocol` appears to use `sodium-native`, should it be using `sodium-universal`?

**Comment by coreymt** [comment]
FML

**Comment by DougAnderson444** [comment]
@tjmehta have you tried making a Hypercore using the [dat-sdk](https://github.com/datproject/sdk#compile-with-webpack-webpackconfigjs)? It uses an alias on sodium in the browser to make it work.

**Comment by tjmehta** [comment]
❗️I'll try it out

**Comment by mafintosh** [comment]
works in the browser since a couple of updates
