### ISSUE TITLE
Size of browserify bundle

### ISSUE THREAD

**Issue by arj03** [hypercore-protocol/hypercore#26]
Hi

Wanted to play around with hypercore, as it would allow me to run things in the browser directly instead of node. So I did a simple test.js with this line: var hypercore = require('hypercore'). And did a browserify on it and it returns a 1.1mb large js file. Any idea what I can do to decrease that? I plan to run hypercore on top of level-js, so maybe there are some things I don't really need.

Thanks

**Comment by mafintosh** [comment]
what is the gzipped size of it?

**Comment by arj03** [comment]
267kb

**Comment by pfraze** [comment]
I noticed, my node_modules grew a lot when I added hyperdrive

**Comment by mafintosh** [comment]
267 kb isn't that bad. We can probably trim that a lot by applying more strict versions internally at some point. I'll leave this open for now

**Comment by mafintosh** [comment]
If you wanna help out, compiling a list of the most heavy dependencies in terms of size would be super useful!

**Comment by mafintosh** [comment]
Would be interesting to run some dead-code elimination on it as well to see if that has any impact. I bet 'crypto' bundles a bunch of unneeded js

**Comment by arj03** [comment]
Using disc (https://github.com/hughsk/disc) it seems to be the sum of a large number of dependencies. elliptic is 112k, bn.js is 81, hash is 27, readable-stream is 47 etc.

**Comment by arj03** [comment]
There seems to be some duplication going on, readable stream is included twice I see.

**Comment by mafintosh** [comment]
both elliptic and bn.js are from crypto i think and i'm 90% sure we don't need any of that. we basically just need hmacs and hashes (sha256). 

anyone know the modules crypto use to supply those? then we could just use those directly when running in the browser

**Comment by mafintosh** [comment]
maybe @feross knows about good alternatives for o/

**Comment by arj03** [comment]
Uglify takes it down to 824k or 190k gzipped

**Comment by mafintosh** [comment]
Let's say the goal is to get <100kb gzipped

**Comment by feross** [comment]
For comparison, WebTorrent is 76 kb (browserified, uglified, and gzipped).

I would focus on eliminating the duplicate dependencies by sending PRs to get your dependencies using the latest versions, and getting rid of crypto is a good idea too.

**Comment by mafintosh** [comment]
Let goal is to become lighter than WebTorrent haha 👍

**Comment by substack** [comment]
Now:

```
$ browserify .|uglifyjs -cm 2>&1|gzip|wc -c
109342
```

**Comment by mafintosh** [comment]
Dedupped a few more dependencies. We are now at

```
$ browserify .|uglifyjs -cm 2>&1|gzip|wc -c
82968
```

**Comment by creationix** [comment]
> Let goal is to become lighter than WebTorrent haha :+1:

That would be awesome.  Now that the sparse bug is fixed and multiwriter is growing, my main blocker for using dat at work is the giant bundle size on mobile browsers.
