### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by okdistribute** [hypercore-protocol/hypercore#267]
"Where is the best place to find any benchmarks of the performance hit of Hypercore, specially when content is being seeded?" 

(I assume they mean to compare to HTTP or other common methods of fetching/serving content?)

Recent question I couldn't figure out how to answer, short of cloning this repo and running `bench`. Could benchmarks be somehow automatically generated and accessible?

**Comment by mafintosh** [comment]
Ya would be cool!

**Comment by mafintosh** [comment]
Closing for now
