### ISSUE TITLE
hypercore sync status info

### ISSUE THREAD

**Issue by pepbrooks** [hypercore-protocol/hypercore#286]
I know this gets asked every so often, but is there anything new that can be used to determine the status of a sync, whether it is finished, in process, pct complete, how many connections are currently being made, etc?

**Comment by derhuerst** [comment]
Currently, there are `feed.peers`, `feed.stats`, `feed.length`, `feed.downloaded([start], [end])` documented. Is that sufficient for your use case?

**Comment by mafintosh** [comment]
Info API in the works, could be an option there
