### ISSUE TITLE
Hypercore Protocol Animations

### ISSUE THREAD

**Issue by allhailjarjar** [hypercore-protocol/hypercore#297]
Sorry if this isn't the right place to ask, but I couldn't find anywhere else to do so. (Discord wanted my phone number to make an account)

The animations are beautiful on the [How the Hypercore Protocol Works](https://hypercore-protocol.org/protocol/) page. I would like to make similar animations for a project. What program was used to make those?

Thanks

**Comment by J-P-S-O** [comment]
@allhailjarjar I can't help you specifically with the animations because its not my area, but the repo for the website is here:
https://github.com/hypercore-protocol/website

**Comment by mafintosh** [comment]
I made them using keynote on Mac :)

**Comment by allhailjarjar** [comment]
LOL I wouldn't have guessed that. Thank you
