### ISSUE TITLE
Proposal do capnproto integration 

### ISSUE THREAD

**Issue by frank-dspeed** [hypercore-protocol/hypercore#311]
Let me Explain a bit there is a concept called capability based function invocation the concept is simple you send some well known protocol like grpc but faster and then let the remote operate on the local data and not send the data. 

https://github.com/capnproto/node-capnp for a quickstart while https://github.com/capnproto offers much more i only want to open your mind for that so we can distribute capnproto and create this ways distributed functions as a service something like etherium only for your interrest i would love to join the project if you like the concepts 

i also adopted your project into my @stealify/ stack and i fixed your streaming problems with electron and all that as my stealify stack is a interop build tool that is able to integrate fast into any software via multiple interfaces.

**Comment by mafintosh** [comment]
Unsure what you are asking, technically. This repo is for Hypercore technical development. If you want to discuss high level ideas join our Discord. I'm always in https://discord.com/invite/holepunch

**Comment by mafintosh** [comment]
(Closing since not technical, feel free to re-open, if you have a technical question or I misunderstood)
