### ISSUE TITLE
Proposal integrate Query able append only log

### ISSUE THREAD

**Issue by frank-dspeed** [hypercore-protocol/hypercore#312]
https://github.com/frank-dspeed/fleece/tree/697eedd62fe9be72022702ea357c3050ea71f38a

this data structure is called fleece it got now a new license thats why i put that exact commit in here that is pre that license so that version can get used to create a open source integration

this format allows you to exchange less data and keep it query able while streaming its the core of couchbase the fastest most complet database implementation that exists by the way using a lot of nice stuff. Highly distributed powers for example pokemon go profiles so it is used in ultra high low latency traffic situations with petrabyte scale but if you size the cluster correct it can easy handle exabyte i see not much limiting there.

**Comment by mafintosh** [comment]
See https://github.com/hypercore-protocol/hypercore/issues/311#issuecomment-1232584675

**Comment by mafintosh** [comment]
(Closing since not technical, feel free to re-open, if you have a technical question or I misunderstood)
