### ISSUE TITLE
'download-started' event, and isDownloading flag

### ISSUE THREAD

**Issue by pfrazee** [hypercore-protocol/hypercore#33]
It'd be handy to have an event which complements 'download-finished', to say when downloading has started. It would be fired the first time data is downloaded in the feed's lifecycle, or any time new data is downloaded after the conditions that fire 'download-finished'.

It would also be handy to have a boolean attribute, `isDownloading`, to indicate whether blocks are still coming in. It could probably be defined as a getter:

``` js
get isDownloading () { return this._downloaded < this.blocks }
```

**Comment by mafintosh** [comment]
the download events are being reworked into events on the peer list

```
feed.peers <-- array of all active peers for the feed
```

each peer will have download data for that peer (how many bytes etc)

**Comment by mafintosh** [comment]
Closing cause old and lots have changed
