### ISSUE TITLE
Expose raw number of bytes downloaded in a swarm

### ISSUE THREAD

**Issue by watson** [hypercore-protocol/hypercore#46]
It would be useful if there were a way to get the raw number of bytes downloaded in a swarm. This would be very useful if you for instance want to show a progress indicator to a user indicating if something is being downloaded.

Note that this is the number of *raw* downloaded bytes - not verified bytes - as I don't care about the validity of the bytes to show Mbps. Also, not updating this number until a block have been verified would defeat the purpose, as it wouldn't allow me to see if something is happening if the block is very large.

**Comment by juliangruber** [comment]
would attaching speedometer to the `feed.replicate()` stream be an option?

**Comment by watson** [comment]
@juliangruber I'm not sure how that would work? Is that already possible?

**Comment by juliangruber** [comment]
```js
net.createServer(con => {
  const rep = feed.replicate()
  const speed = speedometer()
  const total = 0
  rep.on('data', buf => {
    const bps = speed(buf.length)
    total += buf.length
    console.log({ bps, total })
  })
  con.pipe(rep).pip(con)
})

```

**Comment by watson** [comment]
In my case I have a feed created like so:

```js
```

**Comment by watson** [comment]
In my case I have a feed created like so:

```js
var hypercore = require('hypercore')
var swarm = require('hyperdrive-archive-swarm')

var feed = hypercore(lvlDb).createFeed(key)
swarm(feed)
feed.open(function onOpen (err) {
  // ... logic for processing feed downloads ...
})
```

Could I just add the `feed.repliace()` as the first line in the `onOpen` function and then start listening for `data` events?

What's the overhead of creating a flowing replication feed?

**Comment by juliangruber** [comment]
ah, in this case i think this logic needs to go into the swarm module. cc @karissa

**Comment by juliangruber** [comment]
or its api should be changed to

```js
const sw = swarm()
sw.pipe(feed.replicate()).pipe(sw)
```

**Comment by mafintosh** [comment]
Fixed!
