### ISSUE TITLE
Add gzip to the protocol

### ISSUE THREAD

**Issue by blahah** [hypercore-protocol/hypercore#88]
@mafintosh and I were looking at why some hyperdrive feeds were taking a long time to sync metadata, and found that there's a lot of redundancy in the metadata. @mafintosh gzipped it and reduced ~6MB to a few hundred KB. The conclusion was that, whatever other optimisations might be added to the indexing etc., a simple optimisation that will help in almost all cases is to gzip everything.

@mafintosh - are we talking about gzipping on the fly during transport, or gzipping the metadata on disk?

**Comment by mafintosh** [comment]
Just transport for now. Disk is cheap.

**Comment by blahah** [comment]
Recording discussion from IRC:

- @mafintosh suggested trying other compression algorithms - e.g. snappy
- @yoshuawuyts suggested looking at brotli
- we probably want to optimise for slower connections, since that's where large metadata will impact the user experience most
- that likely means preferring a higher compression ratio over faster compression speed
- benchmark all of this

**Comment by emilbayes** [comment]
Just throwing [zstd](https://github.com/facebook/zstd) in the mix :)

**Comment by blahah** [comment]
@emilbayes nice

Also looking at:

- [lzturbo](https://sites.google.com/site/powturbo/home), especially `lzturbo -31` 
- [lz4](https://github.com/lz4/lz4)

**Comment by blahah** [comment]
Here's a pair of hyperdrive v8 keys that can be used to test: https://github.com/codeforscience/sciencefair-elife/issues/1

One is ~3.6k small JSON files, the other is ~3.6k academic papers in JATS xml format with figures in jpg.

**Comment by blahah** [comment]
@mafintosh some v8 feeds that have flat dir structure:

- json `538ff422e03f2b748421a347cb547b9d547297cdecfb267548c0ae32f907bdf7`
- articles `4e3f9a83f8b5bdd193b0c805196fa8db9878ef5efcfafced86fbbd7013d32585`

**Comment by blahah** [comment]
@mafintosh you said compression is now added to append-tree right?

**Comment by joehand** [comment]
To update: this hasn't been added anywhere yet. Bigger priorities like multiwriter =).

**Comment by mafintosh** [comment]
Still interesting! Join the discord if y'all wanna discuss further.
