### ISSUE TITLE
"Transactions": start, append, commit or rollback

### ISSUE THREAD

**Issue by pfrazee** [hypercore-protocol/hypercore#89]
One idea that's been floating around is, being able to make local updates that aren't replicated into the network until the user "commits" them.

"Transactions" would make a simple API for this:

```js
feed.startTransaction()
feed.append('hello')
feed.append('world')
feed.getTransaction(function (err, info) {
  console.log(info.start) // starting seq
  console.log(info.blocks) // 2
})
if (looksGoodManDotJpeg) {
  feed.commitTransaction()
} else {
  feed.abortTransaction()
}
```

The transaction state would be stored to disk so that a transaction would resume if the process is closed and restarted.

In beaker, this would be really handy because users could do development locally, and then only publish by committing when they're ready. In hyperdrive, we might consider adding a 'compress' flag to the commit operation, which would remove any redundant writes (if 'index.html' is updated twice, only the latest write is commited).

**Comment by mafintosh** [comment]
There is landing a super simple version of this soon actually where
writestreams will get an "atomic: true" option. Can prob be expanded in the
future to a more fancy transaction api

**Comment by pfrazee** [comment]
I'd be fine with any API at the hypercore level, it's hyperdrive where I really need the API I suggested here (transactions which can last across app restarts)

**Comment by scriptjs** [comment]
I like the idea this would be at they hypercore level where it can work hand in hand with SLEEP.

**Comment by mafintosh** [comment]
Working on something like this actually, but a lot simpler API (just same as Hypercores api but a batch session)
